# File: .github/workflows/workflow.yml

on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/50a4f952-4988-4d3b-acc8-ed171db2e741/resourceGroups/contoso-traders-rg1729127               
        scopes-ignore: |
          /subscriptions/50a4f952-4988-4d3b-acc8-ed171db2e741/resourceGroups/contoso-traders-rg1729127/providers/microsoft.authorization
     
